export const sawSpecs = {
  model: "HA-38SA",
  cuttingCapacity: {
    width: 400,
    height: 380,
  },
  bladeSpeed: [21, 36, 46, 68],
  sawBladeSpecific: {
    length: 4115,
    width: 34,
    thickness: 1.1,
  },
  voltage: {
    value: 380,
    frequency: 50,
    phase: 3,
  },
  mainMotor: 3,
  hydraulicMotor: 0.55,
  coolingMotor: 0.04,
  sawBladeTensionWay: "Manual",
  chipRemoveWay: "Manual",
  viceClampWay: "Hydraulic",
  hydraulicOilTank: 40,
  weight: 1200,
  machineSize: {
    length: 2100,
    width: 1300,
    height: 1450,
  },
  images: [
    "./bandsaw-machines/HA-38SA/1.jpg",
    "./bandsaw-machines/HA-38SA/2.jpg",
    "./bandsaw-machines/HA-38SA/3.jpg",
    "./bandsaw-machines/HA-38SA/4.jpg",
    "./bandsaw-machines/HA-38SA/5.jpg",
    "./bandsaw-machines/HA-38SA/6.jpg",
    "./bandsaw-machines/HA-38SA/7.jpg",
    "./bandsaw-machines/HA-38SA/8.jpg",
    "./bandsaw-machines/HA-38SA/9.jpg",
    "./bandsaw-machines/HA-38SA/10.jpg",
  ],
  videos: ["./bandsaw-machines/HA-38SA/Video HA-38SA.mp4"],
  homescreenImage: "./bandsaw-machines/HA-38SA/Front-page-image/HA-38SA.png",
};
