export const sawSpecs = {
  model: "HA+-28SA",
  cuttingCapacity: {
    width: 400,
    height: 280,
  },
  bladeSpeed: [25, 35, 45, 60, 80],
  sawBladeSpecific: {
    length: 3505,
    width: 27,
    thickness: 0.9,
  },
  voltage: {
    value: 380,
    frequency: 50,
    phase: 3,
  },
  mainMotor: 2.2,
  hydraulicMotor: 0.37,
  coolingMotor: 0.06,
  sawBladeTensionWay: "Manual",
  viceClampWay: "Manual with hydraulic",
  fastFallingDownPole: ["Sensor", "Hydraulic"],
  hydraulicOilTank: 40,
  weight: 800,
  machineSize: {
    length: 1770,
    width: 1130,
    height: 1160,
  },
  images: [
    "./1.jpg",
    "./2.jpg",
    "./3.jpg",
    "./4.jpg",
    "./5.jpg",
    "./6.jpg",
    "./7.jpg",
    "./8.jpg",
    "./9.jpg",
    "./10.jpg",
  ],
  videos: ["./Video HA+-28SA.mp4"],
  homescreenImage: "./Front-page-image/HA+-28SA.png",
};
